
//! Autogenerated weights for `community_voting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2025-11-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `emmanuel-ThinkPad-T470-W10DG`, CPU: `Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/parachain-template-runtime/parachain_template_runtime.compact.compressed.wasm
// --pallet
// community-voting
// --extrinsic
// 
// --template
// ./pallets/benchmarking/frame-umbrella-weight-template.hbs
// --output
// ./pallets/community-voting/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::weights_prelude::*;

/// Weight functions needed for `community_voting`.
pub trait WeightInfo {
	fn start_voting() -> Weight;
	fn cast_vote() -> Weight;
	fn end_voting() -> Weight;
	fn cast_vote_no() -> Weight;
}

/// Weights for `community_voting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CommunityVoting::VoteCounts` (r:0 w:1)
	/// Proof: `CommunityVoting::VoteCounts` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::VotingPeriods` (r:0 w:1)
	/// Proof: `CommunityVoting::VotingPeriods` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn start_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 44_544_000 picoseconds.
		Weight::from_parts(90_044_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `CommunityVoting::VotingPeriods` (r:1 w:0)
	/// Proof: `CommunityVoting::VotingPeriods` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::ProposalVotes` (r:1 w:1)
	/// Proof: `CommunityVoting::ProposalVotes` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::VoteCounts` (r:1 w:1)
	/// Proof: `CommunityVoting::VoteCounts` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3522`
		// Minimum execution time: 139_214_000 picoseconds.
		Weight::from_parts(289_579_000, 3522)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `CommunityVoting::VotingPeriods` (r:1 w:0)
	/// Proof: `CommunityVoting::VotingPeriods` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::VoteCounts` (r:1 w:0)
	/// Proof: `CommunityVoting::VoteCounts` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn end_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3497`
		// Minimum execution time: 185_202_000 picoseconds.
		Weight::from_parts(195_086_000, 3497)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `CommunityVoting::VotingPeriods` (r:1 w:0)
	/// Proof: `CommunityVoting::VotingPeriods` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::ProposalVotes` (r:1 w:1)
	/// Proof: `CommunityVoting::ProposalVotes` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::VoteCounts` (r:1 w:1)
	/// Proof: `CommunityVoting::VoteCounts` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn cast_vote_no() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3522`
		// Minimum execution time: 251_736_000 picoseconds.
		Weight::from_parts(342_835_000, 3522)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `CommunityVoting::VoteCounts` (r:0 w:1)
	/// Proof: `CommunityVoting::VoteCounts` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::VotingPeriods` (r:0 w:1)
	/// Proof: `CommunityVoting::VotingPeriods` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn start_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 44_544_000 picoseconds.
		Weight::from_parts(90_044_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `CommunityVoting::VotingPeriods` (r:1 w:0)
	/// Proof: `CommunityVoting::VotingPeriods` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::ProposalVotes` (r:1 w:1)
	/// Proof: `CommunityVoting::ProposalVotes` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::VoteCounts` (r:1 w:1)
	/// Proof: `CommunityVoting::VoteCounts` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3522`
		// Minimum execution time: 139_214_000 picoseconds.
		Weight::from_parts(289_579_000, 3522)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `CommunityVoting::VotingPeriods` (r:1 w:0)
	/// Proof: `CommunityVoting::VotingPeriods` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::VoteCounts` (r:1 w:0)
	/// Proof: `CommunityVoting::VoteCounts` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn end_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3497`
		// Minimum execution time: 185_202_000 picoseconds.
		Weight::from_parts(195_086_000, 3497)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `CommunityVoting::VotingPeriods` (r:1 w:0)
	/// Proof: `CommunityVoting::VotingPeriods` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::ProposalVotes` (r:1 w:1)
	/// Proof: `CommunityVoting::ProposalVotes` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CommunityVoting::VoteCounts` (r:1 w:1)
	/// Proof: `CommunityVoting::VoteCounts` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn cast_vote_no() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `148`
		//  Estimated: `3522`
		// Minimum execution time: 251_736_000 picoseconds.
		Weight::from_parts(342_835_000, 3522)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
