
//! Autogenerated weights for `budget_proposal`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2025-11-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `emmanuel-ThinkPad-T470-W10DG`, CPU: `Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/parachain-template-runtime/parachain_template_runtime.compact.compressed.wasm
// --pallet
// budget_proposal
// --extrinsic
// 
// --template
// ./pallets/benchmarking/frame-umbrella-weight-template.hbs
// --output
// ./pallets/budget-proposal/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::weights_prelude::*;

/// Weight functions needed for `budget_proposal`.
pub trait WeightInfo {
	fn create_proposal() -> Weight;
	fn approve_proposal() -> Weight;
	fn reject_proposal() -> Weight;
	fn create_proposal_with_max_sizes() -> Weight;
}

/// Weights for `budget_proposal` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `BudgetProposal::NextProposalId` (r:1 w:1)
	/// Proof: `BudgetProposal::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BudgetProposal::BudgetProposals` (r:0 w:1)
	/// Proof: `BudgetProposal::BudgetProposals` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
	fn create_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `1493`
		// Minimum execution time: 31_955_000 picoseconds.
		Weight::from_parts(60_093_000, 1493)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `BudgetProposal::BudgetProposals` (r:1 w:1)
	/// Proof: `BudgetProposal::BudgetProposals` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
	fn approve_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `163`
		//  Estimated: `3748`
		// Minimum execution time: 44_546_000 picoseconds.
		Weight::from_parts(98_757_000, 3748)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BudgetProposal::BudgetProposals` (r:1 w:1)
	/// Proof: `BudgetProposal::BudgetProposals` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
	fn reject_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3748`
		// Minimum execution time: 46_923_000 picoseconds.
		Weight::from_parts(96_310_000, 3748)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BudgetProposal::NextProposalId` (r:1 w:1)
	/// Proof: `BudgetProposal::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BudgetProposal::BudgetProposals` (r:0 w:1)
	/// Proof: `BudgetProposal::BudgetProposals` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
	fn create_proposal_with_max_sizes() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `1493`
		// Minimum execution time: 38_667_000 picoseconds.
		Weight::from_parts(64_402_000, 1493)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `BudgetProposal::NextProposalId` (r:1 w:1)
	/// Proof: `BudgetProposal::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BudgetProposal::BudgetProposals` (r:0 w:1)
	/// Proof: `BudgetProposal::BudgetProposals` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
	fn create_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `1493`
		// Minimum execution time: 31_955_000 picoseconds.
		Weight::from_parts(60_093_000, 1493)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `BudgetProposal::BudgetProposals` (r:1 w:1)
	/// Proof: `BudgetProposal::BudgetProposals` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
	fn approve_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `163`
		//  Estimated: `3748`
		// Minimum execution time: 44_546_000 picoseconds.
		Weight::from_parts(98_757_000, 3748)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `BudgetProposal::BudgetProposals` (r:1 w:1)
	/// Proof: `BudgetProposal::BudgetProposals` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
	fn reject_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3748`
		// Minimum execution time: 46_923_000 picoseconds.
		Weight::from_parts(96_310_000, 3748)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `BudgetProposal::NextProposalId` (r:1 w:1)
	/// Proof: `BudgetProposal::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BudgetProposal::BudgetProposals` (r:0 w:1)
	/// Proof: `BudgetProposal::BudgetProposals` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
	fn create_proposal_with_max_sizes() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `1493`
		// Minimum execution time: 38_667_000 picoseconds.
		Weight::from_parts(64_402_000, 1493)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
