
//! Autogenerated weights for `audit_log`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2025-11-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `emmanuel-ThinkPad-T470-W10DG`, CPU: `Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/parachain-template-runtime/parachain_template_runtime.compact.compressed.wasm
// --pallet
// audit_log
// --extrinsic
// 
// --template
// ./pallets/benchmarking/frame-umbrella-weight-template.hbs
// --output
// ./pallets/audit-log/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::weights_prelude::*;

/// Weight functions needed for `audit_log`.
pub trait WeightInfo {
	fn log_activity() -> Weight;
	fn get_audit_entry() -> Weight;
	fn log_activity_with_max_sizes_and_related_ids() -> Weight;
}

/// Weights for `audit_log` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AuditLog::NextEntryId` (r:1 w:1)
	/// Proof: `AuditLog::NextEntryId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AuditLog::AuditLog` (r:0 w:1)
	/// Proof: `AuditLog::AuditLog` (`max_values`: None, `max_size`: Some(651), added: 3126, mode: `MaxEncodedLen`)
	fn log_activity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1493`
		// Minimum execution time: 39_348_000 picoseconds.
		Weight::from_parts(41_534_000, 1493)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AuditLog::AuditLog` (r:1 w:0)
	/// Proof: `AuditLog::AuditLog` (`max_values`: None, `max_size`: Some(651), added: 3126, mode: `MaxEncodedLen`)
	fn get_audit_entry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `4116`
		// Minimum execution time: 28_387_000 picoseconds.
		Weight::from_parts(48_667_000, 4116)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `AuditLog::NextEntryId` (r:1 w:1)
	/// Proof: `AuditLog::NextEntryId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AuditLog::AuditLog` (r:0 w:1)
	/// Proof: `AuditLog::AuditLog` (`max_values`: None, `max_size`: Some(651), added: 3126, mode: `MaxEncodedLen`)
	fn log_activity_with_max_sizes_and_related_ids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1493`
		// Minimum execution time: 40_870_000 picoseconds.
		Weight::from_parts(50_218_000, 1493)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `AuditLog::NextEntryId` (r:1 w:1)
	/// Proof: `AuditLog::NextEntryId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AuditLog::AuditLog` (r:0 w:1)
	/// Proof: `AuditLog::AuditLog` (`max_values`: None, `max_size`: Some(651), added: 3126, mode: `MaxEncodedLen`)
	fn log_activity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1493`
		// Minimum execution time: 39_348_000 picoseconds.
		Weight::from_parts(41_534_000, 1493)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AuditLog::AuditLog` (r:1 w:0)
	/// Proof: `AuditLog::AuditLog` (`max_values`: None, `max_size`: Some(651), added: 3126, mode: `MaxEncodedLen`)
	fn get_audit_entry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `4116`
		// Minimum execution time: 28_387_000 picoseconds.
		Weight::from_parts(48_667_000, 4116)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `AuditLog::NextEntryId` (r:1 w:1)
	/// Proof: `AuditLog::NextEntryId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AuditLog::AuditLog` (r:0 w:1)
	/// Proof: `AuditLog::AuditLog` (`max_values`: None, `max_size`: Some(651), added: 3126, mode: `MaxEncodedLen`)
	fn log_activity_with_max_sizes_and_related_ids() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1493`
		// Minimum execution time: 40_870_000 picoseconds.
		Weight::from_parts(50_218_000, 1493)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
