
//! Autogenerated weights for `government_wallet`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2025-11-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `emmanuel-ThinkPad-T470-W10DG`, CPU: `Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/parachain-template-runtime/parachain_template_runtime.compact.compressed.wasm
// --pallet
// government-wallet
// --extrinsic
// 
// --template
// ./pallets/benchmarking/frame-umbrella-weight-template.hbs
// --output
// ./pallets/government-wallet/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::weights_prelude::*;

/// Weight functions needed for `government_wallet`.
pub trait WeightInfo {
	fn create_wallet() -> Weight;
	fn allocate_funds() -> Weight;
	fn create_wallet_with_max_department() -> Weight;
	fn allocate_funds_max_amount() -> Weight;
}

/// Weights for `government_wallet` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `GovernmentWallet::GovernmentWallets` (r:1 w:1)
	/// Proof: `GovernmentWallet::GovernmentWallets` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `GovernmentWallet::WalletBalances` (r:0 w:1)
	/// Proof: `GovernmentWallet::WalletBalances` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn create_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3647`
		// Minimum execution time: 95_172_000 picoseconds.
		Weight::from_parts(124_118_000, 3647)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `GovernmentWallet::GovernmentWallets` (r:1 w:0)
	/// Proof: `GovernmentWallet::GovernmentWallets` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `GovernmentWallet::WalletBalances` (r:1 w:1)
	/// Proof: `GovernmentWallet::WalletBalances` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn allocate_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3647`
		// Minimum execution time: 99_372_000 picoseconds.
		Weight::from_parts(123_677_000, 3647)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `GovernmentWallet::GovernmentWallets` (r:1 w:1)
	/// Proof: `GovernmentWallet::GovernmentWallets` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `GovernmentWallet::WalletBalances` (r:0 w:1)
	/// Proof: `GovernmentWallet::WalletBalances` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn create_wallet_with_max_department() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3647`
		// Minimum execution time: 108_776_000 picoseconds.
		Weight::from_parts(155_543_000, 3647)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `GovernmentWallet::GovernmentWallets` (r:1 w:0)
	/// Proof: `GovernmentWallet::GovernmentWallets` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `GovernmentWallet::WalletBalances` (r:1 w:1)
	/// Proof: `GovernmentWallet::WalletBalances` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn allocate_funds_max_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3647`
		// Minimum execution time: 114_502_000 picoseconds.
		Weight::from_parts(189_653_000, 3647)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `GovernmentWallet::GovernmentWallets` (r:1 w:1)
	/// Proof: `GovernmentWallet::GovernmentWallets` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `GovernmentWallet::WalletBalances` (r:0 w:1)
	/// Proof: `GovernmentWallet::WalletBalances` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn create_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3647`
		// Minimum execution time: 95_172_000 picoseconds.
		Weight::from_parts(124_118_000, 3647)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `GovernmentWallet::GovernmentWallets` (r:1 w:0)
	/// Proof: `GovernmentWallet::GovernmentWallets` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `GovernmentWallet::WalletBalances` (r:1 w:1)
	/// Proof: `GovernmentWallet::WalletBalances` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn allocate_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3647`
		// Minimum execution time: 99_372_000 picoseconds.
		Weight::from_parts(123_677_000, 3647)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `GovernmentWallet::GovernmentWallets` (r:1 w:1)
	/// Proof: `GovernmentWallet::GovernmentWallets` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `GovernmentWallet::WalletBalances` (r:0 w:1)
	/// Proof: `GovernmentWallet::WalletBalances` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn create_wallet_with_max_department() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3647`
		// Minimum execution time: 108_776_000 picoseconds.
		Weight::from_parts(155_543_000, 3647)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `GovernmentWallet::GovernmentWallets` (r:1 w:0)
	/// Proof: `GovernmentWallet::GovernmentWallets` (`max_values`: None, `max_size`: Some(182), added: 2657, mode: `MaxEncodedLen`)
	/// Storage: `GovernmentWallet::WalletBalances` (r:1 w:1)
	/// Proof: `GovernmentWallet::WalletBalances` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn allocate_funds_max_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3647`
		// Minimum execution time: 114_502_000 picoseconds.
		Weight::from_parts(189_653_000, 3647)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
